# Generated by Django 5.0 on 2023-12-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Release Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
