# Generated by Django 5.0 on 2023-12-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_release_date_movie_imdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='path',
            field=models.FilePathField(allow_folders=True, default='/home/j1roscope/Dev/sangstream_ui/public/logo192.png', path='/home/j1roscope/Dev/sangstream_ui/public/', recursive=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
