# Generated by Django 5.0 on 2023-12-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_post_path_alter_movie_vid_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='post_path',
            field=models.ImageField(null=True, upload_to='../../poster'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vid_path',
            field=models.FileField(null=True, upload_to='../../videos'),
        ),
    ]
