# Generated by Django 5.0 on 2023-12-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movie_post_path_alter_movie_vid_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='post_path',
            field=models.FilePathField(allow_folders=True, default='/home/j1roscope/Dev//download.jpeg', path='/home/j1roscope/Dev//poster/', recursive=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vid_path',
            field=models.FilePathField(allow_folders=True, default='/home/j1roscope/Dev//download.jpeg', path='/home/j1roscope/Dev/videos/', recursive=True),
        ),
    ]
