# Generated by Django 5.0 on 2023-12-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movieuserrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='post_path',
            field=models.FilePathField(allow_folders=True, default='/home/j1roscope/Dev//download.jpeg', path='/home/j1roscope/Dev/poster/', recursive=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vid_path',
            field=models.FilePathField(allow_folders=True, default='/home/j1roscope/Dev//test.mp4', path='/home/j1roscope/Dev/videos/', recursive=True),
        ),
    ]
