# Generated by Django 5.0 on 2023-12-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_movie_post_path_alter_movie_vid_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieuserrelation',
            name='pause_time',
            field=models.DurationField(null=True),
        ),
    ]
