# Generated by Django 5.0 on 2024-01-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_movieuserrelation_pause_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='post_path',
            field=models.FilePathField(allow_folders=True, default='http://localhost:5500//download.jpeg', path='http://localhost:5500/poster/', recursive=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vid_path',
            field=models.FilePathField(allow_folders=True, default='http://localhost:5500//test.mp4', path='http://localhost:5500/videos/', recursive=True),
        ),
    ]
