# Generated by Django 5.0 on 2024-01-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_alter_movie_post_path_alter_movie_vid_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='post_path',
            field=models.URLField(default='http://localhost:5500/poster/download.jpeg'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vid_path',
            field=models.URLField(default='http://localhost:5500/video/test.mp4'),
        ),
    ]
