# Generated by Django 5.0 on 2024-01-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_alter_movie_vid_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('posts', models.ImageField(upload_to='')),
            ],
        ),
    ]
