# Generated by Django 5.0 on 2024-01-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='~/Dev/datastore/poster/download.jpeg', upload_to='~/Dev/datastore/poster/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='post_path',
            field=models.URLField(default='/poster/download.jpeg'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vid_path',
            field=models.URLField(default='/videos/test.mp4'),
        ),
        migrations.AlterField(
            model_name='test',
            name='posts',
            field=models.ImageField(upload_to='test/'),
        ),
    ]
