# Generated by Django 5.0 on 2024-01-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_remove_movie_post_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='vid',
            field=models.FileField(default='~/Dev/datastore/poster/videos/', upload_to='~/Dev/datastore/poster/videos/'),
        ),
    ]
