# Generated by Django 5.0 on 2024-01-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_remove_movie_vid_test_vid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='vid_path',
        ),
        migrations.AddField(
            model_name='movie',
            name='vid',
            field=models.FileField(default='~/Dev/datastore/poster/videos/', upload_to='~/Dev/datastore/poster/videos/'),
        ),
    ]
